//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mygod.Edge.Tool {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mygod.Edge.Tool.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 You have achieved this achievement. 的本地化字符串。
        /// </summary>
        public static string AchievementAchievedHint {
            get {
                return ResourceManager.GetString("AchievementAchievedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coming soon... 的本地化字符串。
        /// </summary>
        public static string AchievementDisabledHint {
            get {
                return ResourceManager.GetString("AchievementDisabledHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JUST TELL ME HOW I CAN GET THIS! 的本地化字符串。
        /// </summary>
        public static string AchievementHelpHint {
            get {
                return ResourceManager.GetString("AchievementHelpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to force (un)lock the achievement? 的本地化字符串。
        /// </summary>
        public static string AchievementUnlockConfirm {
            get {
                return ResourceManager.GetString("AchievementUnlockConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Achievement unlocked: {0} 的本地化字符串。
        /// </summary>
        public static string AchievementUnlocked {
            get {
                return ResourceManager.GetString("AchievementUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Congratulations! You have unlocked an achievement! Go check it out!
        ///Achievement description:  的本地化字符串。
        /// </summary>
        public static string AchievementUnlockedDetails {
            get {
                return ResourceManager.GetString("AchievementUnlockedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: Advanced camera mode will be disabled! {1} will be ignored. To enable this mode, remove @Zoom or set it to a negative value. 的本地化字符串。
        /// </summary>
        public static string AdvancedCameraModeDisabled {
            get {
                return ResourceManager.GetString("AdvancedCameraModeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can only apply the animation to one of the models and then view the model. Please pick a model and add it to model viewer in Draw model tree tab. 的本地化字符串。
        /// </summary>
        public static string ApplyAnimNoModelDescription {
            get {
                return ResourceManager.GetString("ApplyAnimNoModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, there is no model to apply your animation to. 的本地化字符串。
        /// </summary>
        public static string ApplyAnimNoModelTitle {
            get {
                return ResourceManager.GetString("ApplyAnimNoModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Apply changes 的本地化字符串。
        /// </summary>
        public static string ApplyChangesButton {
            get {
                return ResourceManager.GetString("ApplyChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply changes and e_xecute EDGE... 的本地化字符串。
        /// </summary>
        public static string ApplyChangesExecuteButton {
            get {
                return ResourceManager.GetString("ApplyChangesExecuteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ask 的本地化字符串。
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-game-typed EdgeMods cannot overwrite /audio/*. Please use /sfx instead. 的本地化字符串。
        /// </summary>
        public static string AudioOverwriteForbidden {
            get {
                return ResourceManager.GetString("AudioOverwriteForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is not allowed to overwrite /audio/* and use /sfx at the same time. Please choose one of them. 的本地化字符串。
        /// </summary>
        public static string AudioSfxConflict {
            get {
                return ResourceManager.GetString("AudioSfxConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse achievements 的本地化字符串。
        /// </summary>
        public static string BrowseAchievementsTab {
            get {
                return ResourceManager.GetString("BrowseAchievementsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hint: Right click to force (un)lock the achievement. If you are playing EDGE with EdgeTool running in the background, you&apos;ll be able to see the newly-acquired achievements as soon as you get them. 的本地化字符串。
        /// </summary>
        public static string BrowseAchievementsTabHint {
            get {
                return ResourceManager.GetString("BrowseAchievementsTabHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse this file in E_xplorer 的本地化字符串。
        /// </summary>
        public static string BrowseFileInExplorerButton {
            get {
                return ResourceManager.GetString("BrowseFileInExplorerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse the level in _Explorer 的本地化字符串。
        /// </summary>
        public static string BrowseLevelInExplorerItem {
            get {
                return ResourceManager.GetString("BrowseLevelInExplorerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse levels 的本地化字符串。
        /// </summary>
        public static string BrowseLevelsTab {
            get {
                return ResourceManager.GetString("BrowseLevelsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hint: right click on the levels to do something complicated. 的本地化字符串。
        /// </summary>
        public static string BrowseLevelsTabHint {
            get {
                return ResourceManager.GetString("BrowseLevelsTabHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bumper 的本地化字符串。
        /// </summary>
        public static string Bumper {
            get {
                return ResourceManager.GetString("Bumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bumper: Its X/Y-coordinate is not larger than 0 and its Y/X-coordinate is less than level&apos;s length/width! This is known to cause extra blocks or missing blocks around this Bumper. 的本地化字符串。
        /// </summary>
        public static string BumperPositionOutOfRange {
            get {
                return ResourceManager.GetString("BumperPositionOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button: Events for buttons in button sequences will be ignored. 的本地化字符串。
        /// </summary>
        public static string ButtonSequenceEventIgnored {
            get {
                return ResourceManager.GetString("ButtonSequenceEventIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button: Buttons in button sequences will be forced to use StayDown mode. 的本地化字符串。
        /// </summary>
        public static string ButtonSequenceForceStayDownMode {
            get {
                return ResourceManager.GetString("ButtonSequenceForceStayDownMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CameraTrigger: This trigger will be disabled for its @Duration=0. 的本地化字符串。
        /// </summary>
        public static string CameraTriggerDisabled {
            get {
                return ResourceManager.GetString("CameraTriggerDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to check for updates. 的本地化字符串。
        /// </summary>
        public static string CheckForUpdatesFailed {
            get {
                return ResourceManager.GetString("CheckForUpdatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates for _EdgeTool 的本地化字符串。
        /// </summary>
        public static string CheckForUpdatesItem {
            get {
                return ResourceManager.GetString("CheckForUpdatesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cleanup finished. 的本地化字符串。
        /// </summary>
        public static string CleanupFinished {
            get {
                return ResourceManager.GetString("CleanupFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All EdgeMods have been uninstalled temporarily. To re-install them, just click Apply changes again. 的本地化字符串。
        /// </summary>
        public static string CleanupFinishedDetails {
            get {
                return ResourceManager.GetString("CleanupFinishedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Clean up all EdgeMods temporarily 的本地化字符串。
        /// </summary>
        public static string CleanUpInstallButton {
            get {
                return ResourceManager.GetString("CleanUpInstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear _history 的本地化字符串。
        /// </summary>
        public static string ClearHistoryButton {
            get {
                return ResourceManager.GetString("ClearHistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error:  的本地化字符串。
        /// </summary>
        public static string CommandLineDecompileError {
            get {
                return ResourceManager.GetString("CommandLineDecompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ------ (De)compiling {0} ------ 的本地化字符串。
        /// </summary>
        public static string CommandLineDecompileHeader {
            get {
                return ResourceManager.GetString("CommandLineDecompileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (De)compiled successfully. 的本地化字符串。
        /// </summary>
        public static string CommandLineDecompileSuccess {
            get {
                return ResourceManager.GetString("CommandLineDecompileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning:  的本地化字符串。
        /// </summary>
        public static string CommandLineDecompileWarning {
            get {
                return ResourceManager.GetString("CommandLineDecompileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (De)_compile 的本地化字符串。
        /// </summary>
        public static string CompileButton {
            get {
                return ResourceManager.GetString("CompileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (De)compile 的本地化字符串。
        /// </summary>
        public static string CompileTab {
            get {
                return ResourceManager.GetString("CompileTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To (de)compile files, just simply drag your files here, or select files from the history at the bottom-left corner. If you are going to compile a level, only the .xml file is needed.
        ///Help: Right click on any file format below to view its document, or 的本地化字符串。
        /// </summary>
        public static string CompileTabHint {
            get {
                return ResourceManager.GetString("CompileTabHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show command line (de)compile help 的本地化字符串。
        /// </summary>
        public static string CompileTabHintShowCommandLineHelpLink {
            get {
                return ResourceManager.GetString("CompileTabHintShowCommandLineHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conversion failed. 的本地化字符串。
        /// </summary>
        public static string ConversionFailed {
            get {
                return ResourceManager.GetString("ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conversion finished. 的本地化字符串。
        /// </summary>
        public static string ConversionFinished {
            get {
                return ResourceManager.GetString("ConversionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} file(s) have been converted. 的本地化字符串。
        /// </summary>
        public static string ConversionFinishedDetails {
            get {
                return ResourceManager.GetString("ConversionFinishedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Convert mobile levels... 的本地化字符串。
        /// </summary>
        public static string ConvertMobileLevelsItem {
            get {
                return ResourceManager.GetString("ConvertMobileLevelsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert to P&amp;C version (uncheck this if you want to convert to mobile version) 的本地化字符串。
        /// </summary>
        public static string ConvertToPcBox {
            get {
                return ResourceManager.GetString("ConvertToPcBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (De)compile 的本地化字符串。
        /// </summary>
        public static string Decompile {
            get {
                return ResourceManager.GetString("Decompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to decompile {0}. 的本地化字符串。
        /// </summary>
        public static string DecompileFailed {
            get {
                return ResourceManager.GetString("DecompileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select files to (de)compile 的本地化字符串。
        /// </summary>
        public static string DecompileFileSelectorTitle {
            get {
                return ResourceManager.GetString("DecompileFileSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished. {0} file(s) have been (de)compiled. 的本地化字符串。
        /// </summary>
        public static string DecompileFinishedDetails {
            get {
                return ResourceManager.GetString("DecompileFinishedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 De_compile the level... 的本地化字符串。
        /// </summary>
        public static string DecompileLevelItem {
            get {
                return ResourceManager.GetString("DecompileLevelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, EdgeTool is unable to recognize the file you are going to (de)compile! 的本地化字符串。
        /// </summary>
        public static string DecompileUnrecognizedFile {
            get {
                return ResourceManager.GetString("DecompileUnrecognizedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete all disabled Edge_Mods 的本地化字符串。
        /// </summary>
        public static string DeleteAllDisabledEdgeModsButton {
            get {
                return ResourceManager.GetString("DeleteAllDisabledEdgeModsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Delete selected EdgeMod 的本地化字符串。
        /// </summary>
        public static string DeleteSelectedEdgeModButton {
            get {
                return ResourceManager.GetString("DeleteSelectedEdgeModButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} is deprecated. Do not use it. 的本地化字符串。
        /// </summary>
        public static string DeprecatedAttribute {
            get {
                return ResourceManager.GetString("DeprecatedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: This element is deprecated. Do not use it. 的本地化字符串。
        /// </summary>
        public static string DeprecatedElement {
            get {
                return ResourceManager.GetString("DeprecatedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw animation tree 的本地化字符串。
        /// </summary>
        public static string DrawAnimTree {
            get {
                return ResourceManager.GetString("DrawAnimTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Draw 的本地化字符串。
        /// </summary>
        public static string DrawButton {
            get {
                return ResourceManager.GetString("DrawButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw _child models 的本地化字符串。
        /// </summary>
        public static string DrawChildModelsBox {
            get {
                return ResourceManager.GetString("DrawChildModelsBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you want to view child models in the model viewer as well, check this box or it might look weird. 的本地化字符串。
        /// </summary>
        public static string DrawChildModelsBoxHint {
            get {
                return ResourceManager.GetString("DrawChildModelsBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Draw model tree 的本地化字符串。
        /// </summary>
        public static string DrawModelTree {
            get {
                return ResourceManager.GetString("DrawModelTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Draw model tree 的本地化字符串。
        /// </summary>
        public static string DrawModelTreeItem {
            get {
                return ResourceManager.GetString("DrawModelTreeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EDGE level files (*.bin) 的本地化字符串。
        /// </summary>
        public static string EdgeLevelFilter {
            get {
                return ResourceManager.GetString("EdgeLevelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        public static string EdgeModAuthor {
            get {
                return ResourceManager.GetString("EdgeModAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string EdgeModEnabled {
            get {
                return ResourceManager.GetString("EdgeModEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred when trying to apply {0}: {1}
        /// 的本地化字符串。
        /// </summary>
        public static string EdgeModError {
            get {
                return ResourceManager.GetString("EdgeModError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} conflicts with {1}! {1} won&apos;t be installed. 的本地化字符串。
        /// </summary>
        public static string EdgeModErrorConflict {
            get {
                return ResourceManager.GetString("EdgeModErrorConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}&apos;s dependencies tree contains loops! This EdgeMod will NOT be installed. 的本地化字符串。
        /// </summary>
        public static string EdgeModErrorDependenciesLoop {
            get {
                return ResourceManager.GetString("EdgeModErrorDependenciesLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some/all of {0}&apos;s dependencies are not installed! 的本地化字符串。
        /// </summary>
        public static string EdgeModErrorEngineDependenciesNotInstalled {
            get {
                return ResourceManager.GetString("EdgeModErrorEngineDependenciesNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} doesn&apos;t support your game engine ({1})! That one won&apos;t be installed. 的本地化字符串。
        /// </summary>
        public static string EdgeModErrorEngineNotSupported {
            get {
                return ResourceManager.GetString("EdgeModErrorEngineNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level-typed EdgeMods are not allowed to overwrite files that comes with the game! Please use @Type=Theme or Game instead if you want to do this. 的本地化字符串。
        /// </summary>
        public static string EdgeModErrorLevelOverwriteForbidden {
            get {
                return ResourceManager.GetString("EdgeModErrorLevelOverwriteForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred when trying to update the level list: {0} 的本地化字符串。
        /// </summary>
        public static string EdgeModErrorXsl {
            get {
                return ResourceManager.GetString("EdgeModErrorXsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred when trying to apply {1} in {0}: {2}
        /// 的本地化字符串。
        /// </summary>
        public static string EdgeModFileError {
            get {
                return ResourceManager.GetString("EdgeModFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID can only consist of letters, numbers, “.”, “_” and “-”! 的本地化字符串。
        /// </summary>
        public static string EdgeModIDMalformed {
            get {
                return ResourceManager.GetString("EdgeModIDMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string EdgeModName {
            get {
                return ResourceManager.GetString("EdgeModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t applied your changes to EdgeMods, so you won&apos;t see the changes after you launch the game. You can press Cancel and click Apply changes to resolve this issue. 的本地化字符串。
        /// </summary>
        public static string EdgeModsChangesNotAppliedMessage {
            get {
                return ResourceManager.GetString("EdgeModsChangesNotAppliedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It might be a little slower to apply the changes for the first time or for the first time after cleaning up. Please wait for a moment. 的本地化字符串。
        /// </summary>
        public static string EdgeModsFirstInstallHint {
            get {
                return ResourceManager.GetString("EdgeModsFirstInstallHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string EdgeModVersion {
            get {
                return ResourceManager.GetString("EdgeModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E_nable debug mode 的本地化字符串。
        /// </summary>
        public static string EnableDebugModeBox {
            get {
                return ResourceManager.GetString("EnableDebugModeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;ll be able to see edges of models in this mode. 的本地化字符串。
        /// </summary>
        public static string EnableDebugModeBoxHint {
            get {
                return ResourceManager.GetString("EnableDebugModeBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter the animation name without the .r_cha extension: 的本地化字符串。
        /// </summary>
        public static string EnterAnimNameLabel {
            get {
                return ResourceManager.GetString("EnterAnimNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter the _model name without the .rmdl extension: 的本地化字符串。
        /// </summary>
        public static string EnterModelNameLabel {
            get {
                return ResourceManager.GetString("EnterModelNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 browse 的本地化字符串。
        /// </summary>
        public static string EnterPath_Browse {
            get {
                return ResourceManager.GetString("EnterPath_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Enter or  的本地化字符串。
        /// </summary>
        public static string EnterPath_EnterOr {
            get {
                return ResourceManager.GetString("EnterPath_EnterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  the path of edge.exe: 的本地化字符串。
        /// </summary>
        public static string EnterPath_YourGamePath {
            get {
                return ResourceManager.GetString("EnterPath_YourGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executable files (*.exe) 的本地化字符串。
        /// </summary>
        public static string ExecutableFilter {
            get {
                return ResourceManager.GetString("ExecutableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit Point 的本地化字符串。
        /// </summary>
        public static string ExitPoint {
            get {
                return ResourceManager.GetString("ExitPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: @Position is same as /Level/@ExitPoint! The actual exit point will be corrupted and the level will be impossible to pass! 的本地化字符串。
        /// </summary>
        public static string ExitPointCorrupted {
            get {
                return ResourceManager.GetString("ExitPointCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level: @ExitPoint is out of the level range! This will cause the game crashing! 的本地化字符串。
        /// </summary>
        public static string ExitPointOutOfRange {
            get {
                return ResourceManager.GetString("ExitPointOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Falling Platform 的本地化字符串。
        /// </summary>
        public static string FallingPlatform {
            get {
                return ResourceManager.GetString("FallingPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FallingPlatform: There is already a static block at {0}! This static block will be corrupted. 的本地化字符串。
        /// </summary>
        public static string FallingPlatformStaticBlock {
            get {
                return ResourceManager.GetString("FallingPlatformStaticBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FallingPlatform: Putting it at {0} will make it visible and un-collidable! Please move the platform or enlarge the level size. 的本地化字符串。
        /// </summary>
        public static string FallingPlatformXYOutOfRange {
            get {
                return ResourceManager.GetString("FallingPlatformXYOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FallingPlatform: Z-coordinate is not larger than ! Player block will be unable to climb or EDGE on this platform! 的本地化字符串。
        /// </summary>
        public static string FallingPlatformZOutOfRange {
            get {
                return ResourceManager.GetString("FallingPlatformZOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FATAL 的本地化字符串。
        /// </summary>
        public static string Fatal {
            get {
                return ResourceManager.GetString("Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What have you done? Please report this and the error messages to bugs.mygod.tk to help us solve the problem. 的本地化字符串。
        /// </summary>
        public static string FatalMessage {
            get {
                return ResourceManager.GetString("FatalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YOU CRASHED MY PROGRAM?! 的本地化字符串。
        /// </summary>
        public static string FatalTitle {
            get {
                return ResourceManager.GetString("FatalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: @Angle and @FieldOfView are both set! @FieldOfView will be ignored. 的本地化字符串。
        /// </summary>
        public static string FieldOfViewIgnored {
            get {
                return ResourceManager.GetString("FieldOfViewIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} already exists. 的本地化字符串。
        /// </summary>
        public static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to overwrite it? 的本地化字符串。
        /// </summary>
        public static string FileAlreadyExistsDetails {
            get {
                return ResourceManager.GetString("FileAlreadyExistsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished 的本地化字符串。
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select edge.exe 的本地化字符串。
        /// </summary>
        public static string GameSelectorTitle {
            get {
                return ResourceManager.GetString("GameSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global player progress:  的本地化字符串。
        /// </summary>
        public static string GlobalPlayerProgress {
            get {
                return ResourceManager.GetString("GlobalPlayerProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        public static string HelpItem {
            get {
                return ResourceManager.GetString("HelpItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} files: {0}... 的本地化字符串。
        /// </summary>
        public static string HistoryList {
            get {
                return ResourceManager.GetString("HistoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (EMPTY) 的本地化字符串。
        /// </summary>
        public static string HistoryListEmpty {
            get {
                return ResourceManager.GetString("HistoryListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicated ID! 的本地化字符串。
        /// </summary>
        public static string IDDuplicated {
            get {
                return ResourceManager.GetString("IDDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID can&apos;t contain any character in “(,)”! 的本地化字符串。
        /// </summary>
        public static string IDInvalidCharacter {
            get {
                return ResourceManager.GetString("IDInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: Incorrect image size. It should be {1}. Its content will not be loaded. 的本地化字符串。
        /// </summary>
        public static string ImageSizeIncorrect {
            get {
                return ResourceManager.GetString("ImageSizeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to install {0}. 的本地化字符串。
        /// </summary>
        public static string InstallEdgeModFailed {
            get {
                return ResourceManager.GetString("InstallEdgeModFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install EdgeMods 的本地化字符串。
        /// </summary>
        public static string InstallEdgeMods {
            get {
                return ResourceManager.GetString("InstallEdgeMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Almost there... 的本地化字符串。
        /// </summary>
        public static string InstallEdgeModsAlmostThere {
            get {
                return ResourceManager.GetString("InstallEdgeModsAlmostThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done. 的本地化字符串。
        /// </summary>
        public static string InstallEdgeModsDone {
            get {
                return ResourceManager.GetString("InstallEdgeModsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installation finished. 的本地化字符串。
        /// </summary>
        public static string InstallEdgeModsFinished {
            get {
                return ResourceManager.GetString("InstallEdgeModsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 But some errors have occurred. Go check it out. 的本地化字符串。
        /// </summary>
        public static string InstallEdgeModsFinishedError {
            get {
                return ResourceManager.GetString("InstallEdgeModsFinishedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparing... 的本地化字符串。
        /// </summary>
        public static string InstallEdgeModsPreparing {
            get {
                return ResourceManager.GetString("InstallEdgeModsPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install EdgeMods 的本地化字符串。
        /// </summary>
        public static string InstallEdgeModsTitle {
            get {
                return ResourceManager.GetString("InstallEdgeModsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid path. 的本地化字符串。
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolkit 的本地化字符串。
        /// </summary>
        public static string JumpListToolkit {
            get {
                return ResourceManager.GetString("JumpListToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates 的本地化字符串。
        /// </summary>
        public static string JumpTaskCheckForUpdates {
            get {
                return ResourceManager.GetString("JumpTaskCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert mobile levels 的本地化字符串。
        /// </summary>
        public static string JumpTaskConvertMobiLevels {
            get {
                return ResourceManager.GetString("JumpTaskConvertMobiLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (De)compile 的本地化字符串。
        /// </summary>
        public static string JumpTaskDecompile {
            get {
                return ResourceManager.GetString("JumpTaskDecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string JumpTaskHelp {
            get {
                return ResourceManager.GetString("JumpTaskHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch EDGE 的本地化字符串。
        /// </summary>
        public static string JumpTaskLaunchGame {
            get {
                return ResourceManager.GetString("JumpTaskLaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record KeyEvent 的本地化字符串。
        /// </summary>
        public static string JumpTaskRecordKeyEvent {
            get {
                return ResourceManager.GetString("JumpTaskRecordKeyEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KeyEvent Recorder 的本地化字符串。
        /// </summary>
        public static string KeyEventRecorder {
            get {
                return ResourceManager.GetString("KeyEventRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press F10 to start, F11 to stop, F12 to stop and discard recorded KeyEvents. 的本地化字符串。
        /// </summary>
        public static string KeyEventRecorderHint {
            get {
                return ResourceManager.GetString("KeyEventRecorderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Initial time: 的本地化字符串。
        /// </summary>
        public static string KeyEventRecorderInitialTime {
            get {
                return ResourceManager.GetString("KeyEventRecorderInitialTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playback _speed: 的本地化字符串。
        /// </summary>
        public static string KeyEventRecorderPlaybackSpeed {
            get {
                return ResourceManager.GetString("KeyEventRecorderPlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Criteria 的本地化字符串。
        /// </summary>
        public static string LevelCriteria {
            get {
                return ResourceManager.GetString("LevelCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit point 的本地化字符串。
        /// </summary>
        public static string LevelExitPoint {
            get {
                return ResourceManager.GetString("LevelExitPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select level .bin files that you want to process 的本地化字符串。
        /// </summary>
        public static string LevelFileSelectorTitle {
            get {
                return ResourceManager.GetString("LevelFileSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level: {2} is wrong! Will be corrected automatically: {0} =&gt; {1} 的本地化字符串。
        /// </summary>
        public static string LevelInvalidArgument {
            get {
                return ResourceManager.GetString("LevelInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The legacy minimap in this level is malformed! It will be ignored automatically. 的本地化字符串。
        /// </summary>
        public static string LevelLegacyMinimapMalformed {
            get {
                return ResourceManager.GetString("LevelLegacyMinimapMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music 的本地化字符串。
        /// </summary>
        public static string LevelMusic {
            get {
                return ResourceManager.GetString("LevelMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Music in Java version 的本地化字符串。
        /// </summary>
        public static string LevelMusicJava {
            get {
                return ResourceManager.GetString("LevelMusicJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string LevelName {
            get {
                return ResourceManager.GetString("LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string LevelPath {
            get {
                return ResourceManager.GetString("LevelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string LevelSize {
            get {
                return ResourceManager.GetString("LevelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spawn point 的本地化字符串。
        /// </summary>
        public static string LevelSpawnPoint {
            get {
                return ResourceManager.GetString("LevelSpawnPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level: Time thresholds for S+, S, A, B, C must be strictly increasing or you may not achieve some of the ranks. 的本地化字符串。
        /// </summary>
        public static string LevelTimeThresholdsAscending {
            get {
                return ResourceManager.GetString("LevelTimeThresholdsAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Load 的本地化字符串。
        /// </summary>
        public static string LoadButton {
            get {
                return ResourceManager.GetString("LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some errors occurred when attempting to load EdgeMods. 的本地化字符串。
        /// </summary>
        public static string LoadEdgeModsError {
            get {
                return ResourceManager.GetString("LoadEdgeModsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading failed. 的本地化字符串。
        /// </summary>
        public static string LoadingFailed {
            get {
                return ResourceManager.GetString("LoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage EdgeMods 的本地化字符串。
        /// </summary>
        public static string ManageEdgeModsTab {
            get {
                return ResourceManager.GetString("ManageEdgeModsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To install the EdgeMod, you can drag the file here, or you can copy/move the file into the mods directory under the game directory and click Refresh. 的本地化字符串。
        /// </summary>
        public static string ManageEdgeModsTabHint {
            get {
                return ResourceManager.GetString("ManageEdgeModsTabHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is not allowed to use /levels/mapping.xsl and/or /mod.xml when you have already overwrited /levels/mapping.xml. Please try to merge your changes into /levels/mapping.xml. 的本地化字符串。
        /// </summary>
        public static string MappingXmlConflict {
            get {
                return ResourceManager.GetString("MappingXmlConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-game-typed EdgeMods cannot overwrite /levels/mapping.xml. Please use /mod.xml or /levels/mapping.xsl instead. 的本地化字符串。
        /// </summary>
        public static string MappingXmlOverwriteForbidden {
            get {
                return ResourceManager.GetString("MappingXmlOverwriteForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is not allowed to use /levels/mapping.xsl and /mod.xml to modify /levels/mapping.xml at the same time! Please try to merge your changes in /mod.xml into /levels/mapping.xsl! 的本地化字符串。
        /// </summary>
        public static string MappingXslConflict {
            get {
                return ResourceManager.GetString("MappingXslConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimap 的本地化字符串。
        /// </summary>
        public static string Minimap {
            get {
                return ResourceManager.GetString("Minimap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal blocks get lighter as they get higher 的本地化字符串。
        /// </summary>
        public static string MinimapHint {
            get {
                return ResourceManager.GetString("MinimapHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save minimap... 的本地化字符串。
        /// </summary>
        public static string MinimapSaveButton {
            get {
                return ResourceManager.GetString("MinimapSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save minimap 的本地化字符串。
        /// </summary>
        public static string MinimapSaveDialogTitle {
            get {
                return ResourceManager.GetString("MinimapSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, EdgeTool is unable to provide full support for this model. 的本地化字符串。
        /// </summary>
        public static string ModelColorWarning {
            get {
                return ResourceManager.GetString("ModelColorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This model has used Models/Model/Triangle/Vertex/@Color which EdgeTool hasn&apos;t supported yet. The model will be rendered in white color. 的本地化字符串。
        /// </summary>
        public static string ModelColorWarningDetails {
            get {
                return ResourceManager.GetString("ModelColorWarningDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model Viewer 的本地化字符串。
        /// </summary>
        public static string ModelViewer {
            get {
                return ResourceManager.GetString("ModelViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hint: Hold left button to drag left, right, forward and backward (X and Z axis). Hold right button to drag up and down (Y axis). Scroll to change Field of View. You can pick background color on the right. 的本地化字符串。
        /// </summary>
        public static string ModelViewerHint {
            get {
                return ResourceManager.GetString("ModelViewerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here if you want to modify mappings.xml manually. 的本地化字符串。
        /// </summary>
        public static string ModifyMappingXmlLink {
            get {
                return ResourceManager.GetString("ModifyMappingXmlLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found: /mod.xml. 的本地化字符串。
        /// </summary>
        public static string ModXmlNotFound {
            get {
                return ResourceManager.GetString("ModXmlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level: @MusicJava is out of range (0-11)! 00_menus will be used. 的本地化字符串。
        /// </summary>
        public static string MusicJavaOutOfRange {
            get {
                return ResourceManager.GetString("MusicJavaOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level: @Music is out of range (0-24)! 06_Kakkoi will be used. 的本地化字符串。
        /// </summary>
        public static string MusicOutOfRange {
            get {
                return ResourceManager.GetString("MusicOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You should use it if you are using the latest Steam non-demo version of the game. 的本地化字符串。
        /// </summary>
        public static string NewEtxConfirmDetails {
            get {
                return ResourceManager.GetString("NewEtxConfirmDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Would you like to use the new version of .etx files? 的本地化字符串。
        /// </summary>
        public static string NewEtxConfirmTitle {
            get {
                return ResourceManager.GetString("NewEtxConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  (NOT EXISTS) 的本地化字符串。
        /// </summary>
        public static string NotExists {
            get {
                return ResourceManager.GetString("NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is currently no updates available. 的本地化字符串。
        /// </summary>
        public static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open settings.ini for EDGE _Demo 的本地化字符串。
        /// </summary>
        public static string OpenSettingsIniEdgeDemoItem {
            get {
                return ResourceManager.GetString("OpenSettingsIniEdgeDemoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open settings.ini for EDGE E_pic 的本地化字符串。
        /// </summary>
        public static string OpenSettingsIniEdgeEpicItem {
            get {
                return ResourceManager.GetString("OpenSettingsIniEdgeEpicItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open settings.ini for ED_GE 的本地化字符串。
        /// </summary>
        public static string OpenSettingsIniEdgeItem {
            get {
                return ResourceManager.GetString("OpenSettingsIniEdgeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select where you want to save 的本地化字符串。
        /// </summary>
        public static string OutputPathSelectorTitle {
            get {
                return ResourceManager.GetString("OutputPathSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG Image (*.png) 的本地化字符串。
        /// </summary>
        public static string PngFilter {
            get {
                return ResourceManager.GetString("PngFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 points 的本地化字符串。
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prism 的本地化字符串。
        /// </summary>
        public static string Prism {
            get {
                return ResourceManager.GetString("Prism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to proceed? 的本地化字符串。
        /// </summary>
        public static string ProceedConfirm {
            get {
                return ResourceManager.GetString("ProceedConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record _KeyEvent 的本地化字符串。
        /// </summary>
        public static string RecordKeyEventItem {
            get {
                return ResourceManager.GetString("RecordKeyEventItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Re_fresh 的本地化字符串。
        /// </summary>
        public static string RefreshEdgeModsButton {
            get {
                return ResourceManager.GetString("RefreshEdgeModsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh _global player progress 的本地化字符串。
        /// </summary>
        public static string RefreshGlobalPlayerProgressButton {
            get {
                return ResourceManager.GetString("RefreshGlobalPlayerProgressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature requires network. 的本地化字符串。
        /// </summary>
        public static string RequireNetworkTooltip {
            get {
                return ResourceManager.GetString("RequireNetworkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enlarger 的本地化字符串。
        /// </summary>
        public static string ResizerGrow {
            get {
                return ResourceManager.GetString("ResizerGrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shrinker 的本地化字符串。
        /// </summary>
        public static string ResizerShrink {
            get {
                return ResourceManager.GetString("ResizerShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resizer{0}: X and/or Y-coordinate is out of range! The resizer will be visible in the level but will neither function nor collide with the player block and might cause the game to crash. 的本地化字符串。
        /// </summary>
        public static string ResizerXYOutOfRange {
            get {
                return ResourceManager.GetString("ResizerXYOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resizer{0}: Z-coordinate is out of range! This could cause the game to crash. 的本地化字符串。
        /// </summary>
        public static string ResizerZOutOfRange {
            get {
                return ResourceManager.GetString("ResizerZOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Run EDGE 的本地化字符串。
        /// </summary>
        public static string RunGameButton {
            get {
                return ResourceManager.GetString("RunGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select _user: 的本地化字符串。
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (How?) 的本地化字符串。
        /// </summary>
        public static string ShowMappingXmlHelpLink {
            get {
                return ResourceManager.GetString("ShowMappingXmlHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show _minimap 的本地化字符串。
        /// </summary>
        public static string ShowMinimapItem {
            get {
                return ResourceManager.GetString("ShowMinimapItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Sort... 的本地化字符串。
        /// </summary>
        public static string SortButton {
            get {
                return ResourceManager.GetString("SortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By _achieved 的本地化字符串。
        /// </summary>
        public static string SortByAchieved {
            get {
                return ResourceManager.GetString("SortByAchieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By AP_I name 的本地化字符串。
        /// </summary>
        public static string SortByApiName {
            get {
                return ResourceManager.GetString("SortByApiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By _description 的本地化字符串。
        /// </summary>
        public static string SortByDescription {
            get {
                return ResourceManager.GetString("SortByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By _global player progress 的本地化字符串。
        /// </summary>
        public static string SortByGlobalPlayerProgress {
            get {
                return ResourceManager.GetString("SortByGlobalPlayerProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By _points 的本地化字符串。
        /// </summary>
        public static string SortByPoints {
            get {
                return ResourceManager.GetString("SortByPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By _title 的本地化字符串。
        /// </summary>
        public static string SortByTitle {
            get {
                return ResourceManager.GetString("SortByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 By default _order 的本地化字符串。
        /// </summary>
        public static string SortDefaultOrder {
            get {
                return ResourceManager.GetString("SortDefaultOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spawn Point 的本地化字符串。
        /// </summary>
        public static string SpawnPoint {
            get {
                return ResourceManager.GetString("SpawnPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level: Z-coordinate of @SpawnPoint is less than -20, the level will stuck restarting itself over and over! 的本地化字符串。
        /// </summary>
        public static string SpawnPointOutOfRange {
            get {
                return ResourceManager.GetString("SpawnPointOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start after (de)compilation: 的本地化字符串。
        /// </summary>
        public static string StartAfterCompileLabel {
            get {
                return ResourceManager.GetString("StartAfterCompileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to start the (de)compiled file. 的本地化字符串。
        /// </summary>
        public static string StartDecompiledFileFailed {
            get {
                return ResourceManager.GetString("StartDecompiledFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to selecte_d profile 的本地化字符串。
        /// </summary>
        public static string SwitchToSelectedProfileButton {
            get {
                return ResourceManager.GetString("SwitchToSelectedProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level: @Theme is out of range (0-3)! White theme (0) will be used. 的本地化字符串。
        /// </summary>
        public static string ThemeOutOfRange {
            get {
                return ResourceManager.GetString("ThemeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Toolbox... 的本地化字符串。
        /// </summary>
        public static string ToolboxButton {
            get {
                return ResourceManager.GetString("ToolboxButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One Triangle must have three Vertex child elements! 的本地化字符串。
        /// </summary>
        public static string TriangleVertexCountError {
            get {
                return ResourceManager.GetString("TriangleVertexCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: Unable to recognize this element under {1} element. It will be ignored. 的本地化字符串。
        /// </summary>
        public static string UnrecognizedChildElement {
            get {
                return ResourceManager.GetString("UnrecognizedChildElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized coordinate! 的本地化字符串。
        /// </summary>
        public static string UnrecognizedCoordinate {
            get {
                return ResourceManager.GetString("UnrecognizedCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized event! 的本地化字符串。
        /// </summary>
        public static string UnrecognizedEvent {
            get {
                return ResourceManager.GetString("UnrecognizedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized level size! 的本地化字符串。
        /// </summary>
        public static string UnrecognizedSize {
            get {
                return ResourceManager.GetString("UnrecognizedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: @Angle or @FieldOfView is larger than 184! 184 will be used for this value. 的本地化字符串。
        /// </summary>
        public static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add _selected models to model viewer 的本地化字符串。
        /// </summary>
        public static string ViewerAddSelectedModelButton {
            get {
                return ResourceManager.GetString("ViewerAddSelectedModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Apply selected animation to all models in model viewer (right click if you want to play only once) 的本地化字符串。
        /// </summary>
        public static string ViewerApplySelectedAnimButton {
            get {
                return ResourceManager.GetString("ViewerApplySelectedAnimButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line 1 Column 1 must be &apos;id&apos;! 的本地化字符串。
        /// </summary>
        public static string XlsFormatIDError {
            get {
                return ResourceManager.GetString("XlsFormatIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: @Zoom is out of range (1-{1})! Zoom level 1 will be used. 的本地化字符串。
        /// </summary>
        public static string ZoomOutOfRange {
            get {
                return ResourceManager.GetString("ZoomOutOfRange", resourceCulture);
            }
        }
    }
}
