//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mygod.Edge.Tool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mygod.Edge.Tool.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have achieved this achievement..
        /// </summary>
        public static string AchievementAchievedHint {
            get {
                return ResourceManager.GetString("AchievementAchievedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon....
        /// </summary>
        public static string AchievementDisabledHint {
            get {
                return ResourceManager.GetString("AchievementDisabledHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUST TELL ME HOW I CAN GET THIS!.
        /// </summary>
        public static string AchievementHelpHint {
            get {
                return ResourceManager.GetString("AchievementHelpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to force (un)lock the achievement?.
        /// </summary>
        public static string AchievementUnlockConfirm {
            get {
                return ResourceManager.GetString("AchievementUnlockConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement unlocked: {0}.
        /// </summary>
        public static string AchievementUnlocked {
            get {
                return ResourceManager.GetString("AchievementUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have unlocked an achievement! Go check it out!
        ///Achievement description: .
        /// </summary>
        public static string AchievementUnlockedDetails {
            get {
                return ResourceManager.GetString("AchievementUnlockedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Advanced camera mode will be disabled! {1} will be ignored. To enable this mode, remove @Zoom or set it to a negative value..
        /// </summary>
        public static string AdvancedCameraModeDisabled {
            get {
                return ResourceManager.GetString("AdvancedCameraModeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there....
        /// </summary>
        public static string AlmostThere {
            get {
                return ResourceManager.GetString("AlmostThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only apply the animation to one of the models and then view the model. Please pick a model and add it to model viewer in Draw model tree tab..
        /// </summary>
        public static string ApplyAnimNoModelDescription {
            get {
                return ResourceManager.GetString("ApplyAnimNoModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is no model to apply your animation to..
        /// </summary>
        public static string ApplyAnimNoModelTitle {
            get {
                return ResourceManager.GetString("ApplyAnimNoModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Apply changes.
        /// </summary>
        public static string ApplyChangesButton {
            get {
                return ResourceManager.GetString("ApplyChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes and e_xecute EDGE....
        /// </summary>
        public static string ApplyChangesExecuteButton {
            get {
                return ResourceManager.GetString("ApplyChangesExecuteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-game-typed EdgeMods cannot overwrite /audio/*. Please use /sfx instead..
        /// </summary>
        public static string AudioOverwriteForbidden {
            get {
                return ResourceManager.GetString("AudioOverwriteForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to overwrite /audio/* and use /sfx at the same time. Please choose one of them..
        /// </summary>
        public static string AudioSfxConflict {
            get {
                return ResourceManager.GetString("AudioSfxConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse achievements.
        /// </summary>
        public static string BrowseAchievementsTab {
            get {
                return ResourceManager.GetString("BrowseAchievementsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: Right click to force (un)lock the achievement. If you are playing EDGE with EdgeTool running in the background, you&apos;ll be able to see the newly-acquired achievements as soon as you get them..
        /// </summary>
        public static string BrowseAchievementsTabHint {
            get {
                return ResourceManager.GetString("BrowseAchievementsTabHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse this file in E_xplorer.
        /// </summary>
        public static string BrowseFileInExplorerButton {
            get {
                return ResourceManager.GetString("BrowseFileInExplorerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse the level in _Explorer.
        /// </summary>
        public static string BrowseLevelInExplorerItem {
            get {
                return ResourceManager.GetString("BrowseLevelInExplorerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse levels.
        /// </summary>
        public static string BrowseLevelsTab {
            get {
                return ResourceManager.GetString("BrowseLevelsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: right click on the levels to do something complicated..
        /// </summary>
        public static string BrowseLevelsTabHint {
            get {
                return ResourceManager.GetString("BrowseLevelsTabHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumper.
        /// </summary>
        public static string Bumper {
            get {
                return ResourceManager.GetString("Bumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumper: Its X/Y-coordinate is not larger than 0 and its Y/X-coordinate is less than level&apos;s length/width! This is known to cause extra blocks or missing blocks around this Bumper..
        /// </summary>
        public static string BumperPositionOutOfRange {
            get {
                return ResourceManager.GetString("BumperPositionOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button: Events for buttons in button sequences will be ignored..
        /// </summary>
        public static string ButtonSequenceEventIgnored {
            get {
                return ResourceManager.GetString("ButtonSequenceEventIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button: Buttons in button sequences will be forced to use StayDown mode..
        /// </summary>
        public static string ButtonSequenceForceStayDownMode {
            get {
                return ResourceManager.GetString("ButtonSequenceForceStayDownMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraTrigger: This trigger will be disabled for its @Duration=0..
        /// </summary>
        public static string CameraTriggerDisabled {
            get {
                return ResourceManager.GetString("CameraTriggerDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates..
        /// </summary>
        public static string CheckForUpdatesFailed {
            get {
                return ResourceManager.GetString("CheckForUpdatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates for _EdgeTool.
        /// </summary>
        public static string CheckForUpdatesItem {
            get {
                return ResourceManager.GetString("CheckForUpdatesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup finished..
        /// </summary>
        public static string CleanupFinished {
            get {
                return ResourceManager.GetString("CleanupFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All EdgeMods have been uninstalled temporarily. To re-install them, just click Apply changes again..
        /// </summary>
        public static string CleanupFinishedDetails {
            get {
                return ResourceManager.GetString("CleanupFinishedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clean up all EdgeMods temporarily.
        /// </summary>
        public static string CleanUpInstallButton {
            get {
                return ResourceManager.GetString("CleanUpInstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear _history.
        /// </summary>
        public static string ClearHistoryButton {
            get {
                return ResourceManager.GetString("ClearHistoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string CommandLineDecompileError {
            get {
                return ResourceManager.GetString("CommandLineDecompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------ (De)compiling {0} ------.
        /// </summary>
        public static string CommandLineDecompileHeader {
            get {
                return ResourceManager.GetString("CommandLineDecompileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (De)compiled successfully..
        /// </summary>
        public static string CommandLineDecompileSuccess {
            get {
                return ResourceManager.GetString("CommandLineDecompileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: .
        /// </summary>
        public static string CommandLineDecompileWarning {
            get {
                return ResourceManager.GetString("CommandLineDecompileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (De)_compile.
        /// </summary>
        public static string CompileButton {
            get {
                return ResourceManager.GetString("CompileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compile mobile version..
        /// </summary>
        public static string CompileMobileVersionFailed {
            get {
                return ResourceManager.GetString("CompileMobileVersionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile mobile _version....
        /// </summary>
        public static string CompileMobileVersionItem {
            get {
                return ResourceManager.GetString("CompileMobileVersionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling mobile version....
        /// </summary>
        public static string CompileMobileVersionTitle {
            get {
                return ResourceManager.GetString("CompileMobileVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (De)compile.
        /// </summary>
        public static string CompileTab {
            get {
                return ResourceManager.GetString("CompileTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To (de)compile files, just simply drag your files here, or select files from the history at the bottom-left corner. If you are going to compile a level, only the .xml file is needed.
        ///Help: Right click on any file format below to view its document, or.
        /// </summary>
        public static string CompileTabHint {
            get {
                return ResourceManager.GetString("CompileTabHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show command line (de)compile help.
        /// </summary>
        public static string CompileTabHintShowCommandLineHelpLink {
            get {
                return ResourceManager.GetString("CompileTabHintShowCommandLineHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion failed..
        /// </summary>
        public static string ConversionFailed {
            get {
                return ResourceManager.GetString("ConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion finished..
        /// </summary>
        public static string ConversionFinished {
            get {
                return ResourceManager.GetString("ConversionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) have been converted..
        /// </summary>
        public static string ConversionFinishedDetails {
            get {
                return ResourceManager.GetString("ConversionFinishedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Convert mobile levels....
        /// </summary>
        public static string ConvertMobileLevelsItem {
            get {
                return ResourceManager.GetString("ConvertMobileLevelsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to P&amp;C version (uncheck this if you want to convert to mobile version).
        /// </summary>
        public static string ConvertToPcBox {
            get {
                return ResourceManager.GetString("ConvertToPcBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (De)compile.
        /// </summary>
        public static string Decompile {
            get {
                return ResourceManager.GetString("Decompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to decompile {0}..
        /// </summary>
        public static string DecompileFailed {
            get {
                return ResourceManager.GetString("DecompileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files to (de)compile.
        /// </summary>
        public static string DecompileFileSelectorTitle {
            get {
                return ResourceManager.GetString("DecompileFileSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished. {0} file(s) have been (de)compiled..
        /// </summary>
        public static string DecompileFinishedDetails {
            get {
                return ResourceManager.GetString("DecompileFinishedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De_compile the level....
        /// </summary>
        public static string DecompileLevelItem {
            get {
                return ResourceManager.GetString("DecompileLevelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, EdgeTool is unable to recognize the file you are going to (de)compile!.
        /// </summary>
        public static string DecompileUnrecognizedFile {
            get {
                return ResourceManager.GetString("DecompileUnrecognizedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all disabled Edge_Mods.
        /// </summary>
        public static string DeleteAllDisabledEdgeModsButton {
            get {
                return ResourceManager.GetString("DeleteAllDisabledEdgeModsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete selected EdgeMod.
        /// </summary>
        public static string DeleteSelectedEdgeModButton {
            get {
                return ResourceManager.GetString("DeleteSelectedEdgeModButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} is deprecated. Do not use it..
        /// </summary>
        public static string DeprecatedAttribute {
            get {
                return ResourceManager.GetString("DeprecatedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: This element is deprecated. Do not use it..
        /// </summary>
        public static string DeprecatedElement {
            get {
                return ResourceManager.GetString("DeprecatedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw animation tree.
        /// </summary>
        public static string DrawAnimTree {
            get {
                return ResourceManager.GetString("DrawAnimTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Draw.
        /// </summary>
        public static string DrawButton {
            get {
                return ResourceManager.GetString("DrawButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw _child models.
        /// </summary>
        public static string DrawChildModelsBox {
            get {
                return ResourceManager.GetString("DrawChildModelsBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to view child models in the model viewer as well, check this box or it might look weird..
        /// </summary>
        public static string DrawChildModelsBoxHint {
            get {
                return ResourceManager.GetString("DrawChildModelsBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw model tree.
        /// </summary>
        public static string DrawModelTree {
            get {
                return ResourceManager.GetString("DrawModelTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Draw model tree.
        /// </summary>
        public static string DrawModelTreeItem {
            get {
                return ResourceManager.GetString("DrawModelTreeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDGE level files.
        /// </summary>
        public static string EdgeLevelFilter {
            get {
                return ResourceManager.GetString("EdgeLevelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string EdgeModAuthor {
            get {
                return ResourceManager.GetString("EdgeModAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string EdgeModEnabled {
            get {
                return ResourceManager.GetString("EdgeModEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when trying to apply {0}: {1}
        ///.
        /// </summary>
        public static string EdgeModError {
            get {
                return ResourceManager.GetString("EdgeModError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} conflicts with {1}! {1} won&apos;t be installed..
        /// </summary>
        public static string EdgeModErrorConflict {
            get {
                return ResourceManager.GetString("EdgeModErrorConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s dependencies tree contains loops! This EdgeMod will NOT be installed..
        /// </summary>
        public static string EdgeModErrorDependenciesLoop {
            get {
                return ResourceManager.GetString("EdgeModErrorDependenciesLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some/all of {0}&apos;s dependencies are not installed!.
        /// </summary>
        public static string EdgeModErrorEngineDependenciesNotInstalled {
            get {
                return ResourceManager.GetString("EdgeModErrorEngineDependenciesNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t support your game engine ({1})! That one won&apos;t be installed..
        /// </summary>
        public static string EdgeModErrorEngineNotSupported {
            get {
                return ResourceManager.GetString("EdgeModErrorEngineNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level-typed EdgeMods are not allowed to overwrite files that comes with the game! Please use @Type=Theme or Game instead if you want to do this..
        /// </summary>
        public static string EdgeModErrorLevelOverwriteForbidden {
            get {
                return ResourceManager.GetString("EdgeModErrorLevelOverwriteForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when trying to update the level list: {0}.
        /// </summary>
        public static string EdgeModErrorXsl {
            get {
                return ResourceManager.GetString("EdgeModErrorXsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred when trying to apply {1} in {0}: {2}
        ///.
        /// </summary>
        public static string EdgeModFileError {
            get {
                return ResourceManager.GetString("EdgeModFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID can only consist of letters, numbers, “.”, “_” and “-”!.
        /// </summary>
        public static string EdgeModIDMalformed {
            get {
                return ResourceManager.GetString("EdgeModIDMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EdgeModName {
            get {
                return ResourceManager.GetString("EdgeModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t applied your changes to EdgeMods, so you won&apos;t see the changes after you launch the game. You can press Cancel and click Apply changes to resolve this issue..
        /// </summary>
        public static string EdgeModsChangesNotAppliedMessage {
            get {
                return ResourceManager.GetString("EdgeModsChangesNotAppliedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It might be a little slower to apply the changes for the first time or for the first time after cleaning up. Please wait for a moment..
        /// </summary>
        public static string EdgeModsFirstInstallHint {
            get {
                return ResourceManager.GetString("EdgeModsFirstInstallHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string EdgeModVersion {
            get {
                return ResourceManager.GetString("EdgeModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_nable debug mode.
        /// </summary>
        public static string EnableDebugModeBox {
            get {
                return ResourceManager.GetString("EnableDebugModeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll be able to see edges of models in this mode..
        /// </summary>
        public static string EnableDebugModeBoxHint {
            get {
                return ResourceManager.GetString("EnableDebugModeBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the animation name without the .r_cha extension:.
        /// </summary>
        public static string EnterAnimNameLabel {
            get {
                return ResourceManager.GetString("EnterAnimNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the _model name without the .rmdl extension:.
        /// </summary>
        public static string EnterModelNameLabel {
            get {
                return ResourceManager.GetString("EnterModelNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse.
        /// </summary>
        public static string EnterPath_Browse {
            get {
                return ResourceManager.GetString("EnterPath_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Enter or .
        /// </summary>
        public static string EnterPath_EnterOr {
            get {
                return ResourceManager.GetString("EnterPath_EnterOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  the path of edge.exe:.
        /// </summary>
        public static string EnterPath_YourGamePath {
            get {
                return ResourceManager.GetString("EnterPath_YourGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files.
        /// </summary>
        public static string ExecutableFilter {
            get {
                return ResourceManager.GetString("ExecutableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Point.
        /// </summary>
        public static string ExitPoint {
            get {
                return ResourceManager.GetString("ExitPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: @Position is same as /Level/@ExitPoint! The actual exit point will be corrupted and the level will be impossible to pass!.
        /// </summary>
        public static string ExitPointCorrupted {
            get {
                return ResourceManager.GetString("ExitPointCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: @ExitPoint is out of the level range! This will cause the game crashing!.
        /// </summary>
        public static string ExitPointOutOfRange {
            get {
                return ResourceManager.GetString("ExitPointOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falling Platform.
        /// </summary>
        public static string FallingPlatform {
            get {
                return ResourceManager.GetString("FallingPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FallingPlatform: {0} is out of level boundaries. Player block will not be able to  climb from/to this block! Please move the platform or enlarge the level size..
        /// </summary>
        public static string FallingPlatformOutOfRange {
            get {
                return ResourceManager.GetString("FallingPlatformOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FallingPlatform: There is already a static block at {0}! This static block will be corrupted..
        /// </summary>
        public static string FallingPlatformStaticBlock {
            get {
                return ResourceManager.GetString("FallingPlatformStaticBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FallingPlatform: Putting it at {0} will make it visible and un-collidable! Please move the platform or enlarge the level size..
        /// </summary>
        public static string FallingPlatformXYOutOfRange {
            get {
                return ResourceManager.GetString("FallingPlatformXYOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATAL.
        /// </summary>
        public static string Fatal {
            get {
                return ResourceManager.GetString("Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report to: https://github.com/Mygod/EDGE/issues.
        /// </summary>
        public static string FatalMessage {
            get {
                return ResourceManager.GetString("FatalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU CRASHED MY PROGRAM?!.
        /// </summary>
        public static string FatalTitle {
            get {
                return ResourceManager.GetString("FatalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: @Angle and @FieldOfView are both set! @FieldOfView will be ignored..
        /// </summary>
        public static string FieldOfViewIgnored {
            get {
                return ResourceManager.GetString("FieldOfViewIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        public static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite it?.
        /// </summary>
        public static string FileAlreadyExistsDetails {
            get {
                return ResourceManager.GetString("FileAlreadyExistsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select edge.exe.
        /// </summary>
        public static string GameSelectorTitle {
            get {
                return ResourceManager.GetString("GameSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global player progress: .
        /// </summary>
        public static string GlobalPlayerProgress {
            get {
                return ResourceManager.GetString("GlobalPlayerProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpItem {
            get {
                return ResourceManager.GetString("HelpItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} files: {0}....
        /// </summary>
        public static string HistoryList {
            get {
                return ResourceManager.GetString("HistoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (EMPTY).
        /// </summary>
        public static string HistoryListEmpty {
            get {
                return ResourceManager.GetString("HistoryListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated ID!.
        /// </summary>
        public static string IDDuplicated {
            get {
                return ResourceManager.GetString("IDDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID can&apos;t contain any character in “(,)”!.
        /// </summary>
        public static string IDInvalidCharacter {
            get {
                return ResourceManager.GetString("IDInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Incorrect image size. It should be {1}. Its content will not be loaded..
        /// </summary>
        public static string ImageSizeIncorrect {
            get {
                return ResourceManager.GetString("ImageSizeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install {0}..
        /// </summary>
        public static string InstallEdgeModFailed {
            get {
                return ResourceManager.GetString("InstallEdgeModFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install EdgeMods.
        /// </summary>
        public static string InstallEdgeMods {
            get {
                return ResourceManager.GetString("InstallEdgeMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation finished..
        /// </summary>
        public static string InstallEdgeModsFinished {
            get {
                return ResourceManager.GetString("InstallEdgeModsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But some errors have occurred. Go check it out..
        /// </summary>
        public static string InstallEdgeModsFinishedError {
            get {
                return ResourceManager.GetString("InstallEdgeModsFinishedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install EdgeMods.
        /// </summary>
        public static string InstallEdgeModsTitle {
            get {
                return ResourceManager.GetString("InstallEdgeModsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path..
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit.
        /// </summary>
        public static string JumpListToolkit {
            get {
                return ResourceManager.GetString("JumpListToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string JumpTaskCheckForUpdates {
            get {
                return ResourceManager.GetString("JumpTaskCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert mobile levels.
        /// </summary>
        public static string JumpTaskConvertMobiLevels {
            get {
                return ResourceManager.GetString("JumpTaskConvertMobiLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (De)compile.
        /// </summary>
        public static string JumpTaskDecompile {
            get {
                return ResourceManager.GetString("JumpTaskDecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string JumpTaskHelp {
            get {
                return ResourceManager.GetString("JumpTaskHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch EDGE.
        /// </summary>
        public static string JumpTaskLaunchGame {
            get {
                return ResourceManager.GetString("JumpTaskLaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record KeyEvent.
        /// </summary>
        public static string JumpTaskRecordKeyEvent {
            get {
                return ResourceManager.GetString("JumpTaskRecordKeyEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyEvent Recorder.
        /// </summary>
        public static string KeyEventRecorder {
            get {
                return ResourceManager.GetString("KeyEventRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F10 to start, F11 to stop, F12 to stop and discard recorded KeyEvents..
        /// </summary>
        public static string KeyEventRecorderHint {
            get {
                return ResourceManager.GetString("KeyEventRecorderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Initial time:.
        /// </summary>
        public static string KeyEventRecorderInitialTime {
            get {
                return ResourceManager.GetString("KeyEventRecorderInitialTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback _speed:.
        /// </summary>
        public static string KeyEventRecorderPlaybackSpeed {
            get {
                return ResourceManager.GetString("KeyEventRecorderPlaybackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string LevelCriteria {
            get {
                return ResourceManager.GetString("LevelCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit point.
        /// </summary>
        public static string LevelExitPoint {
            get {
                return ResourceManager.GetString("LevelExitPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select level .bin files that you want to process.
        /// </summary>
        public static string LevelFileSelectorTitle {
            get {
                return ResourceManager.GetString("LevelFileSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: {2} is wrong! Will be corrected automatically: {0} =&gt; {1}.
        /// </summary>
        public static string LevelInvalidArgument {
            get {
                return ResourceManager.GetString("LevelInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The legacy minimap in this level is malformed! It will be ignored automatically..
        /// </summary>
        public static string LevelLegacyMinimapMalformed {
            get {
                return ResourceManager.GetString("LevelLegacyMinimapMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string LevelMusic {
            get {
                return ResourceManager.GetString("LevelMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music in Java version.
        /// </summary>
        public static string LevelMusicJava {
            get {
                return ResourceManager.GetString("LevelMusicJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LevelName {
            get {
                return ResourceManager.GetString("LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string LevelPath {
            get {
                return ResourceManager.GetString("LevelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string LevelSize {
            get {
                return ResourceManager.GetString("LevelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn point.
        /// </summary>
        public static string LevelSpawnPoint {
            get {
                return ResourceManager.GetString("LevelSpawnPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: Time thresholds for S+, S, A, B, C must be strictly increasing or you may not achieve some of the ranks..
        /// </summary>
        public static string LevelTimeThresholdsAscending {
            get {
                return ResourceManager.GetString("LevelTimeThresholdsAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load.
        /// </summary>
        public static string LoadButton {
            get {
                return ResourceManager.GetString("LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors occurred when attempting to load EdgeMods..
        /// </summary>
        public static string LoadEdgeModsError {
            get {
                return ResourceManager.GetString("LoadEdgeModsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading failed..
        /// </summary>
        public static string LoadingFailed {
            get {
                return ResourceManager.GetString("LoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage EdgeMods.
        /// </summary>
        public static string ManageEdgeModsTab {
            get {
                return ResourceManager.GetString("ManageEdgeModsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To install the EdgeMod, you can drag the file here, or you can copy/move the file into the mods directory under the game directory and click Refresh..
        /// </summary>
        public static string ManageEdgeModsTabHint {
            get {
                return ResourceManager.GetString("ManageEdgeModsTabHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to use /levels/mapping.xsl and/or /mod.xml when you have already overwrited /levels/mapping.xml. Please try to merge your changes into /levels/mapping.xml..
        /// </summary>
        public static string MappingXmlConflict {
            get {
                return ResourceManager.GetString("MappingXmlConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-game-typed EdgeMods cannot overwrite /levels/mapping.xml. Please use /mod.xml or /levels/mapping.xsl instead..
        /// </summary>
        public static string MappingXmlOverwriteForbidden {
            get {
                return ResourceManager.GetString("MappingXmlOverwriteForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to use /levels/mapping.xsl and /mod.xml to modify /levels/mapping.xml at the same time! Please try to merge your changes in /mod.xml into /levels/mapping.xsl!.
        /// </summary>
        public static string MappingXslConflict {
            get {
                return ResourceManager.GetString("MappingXslConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimap.
        /// </summary>
        public static string Minimap {
            get {
                return ResourceManager.GetString("Minimap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal blocks get lighter as they get higher.
        /// </summary>
        public static string MinimapHint {
            get {
                return ResourceManager.GetString("MinimapHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save minimap....
        /// </summary>
        public static string MinimapSaveButton {
            get {
                return ResourceManager.GetString("MinimapSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save minimap.
        /// </summary>
        public static string MinimapSaveDialogTitle {
            get {
                return ResourceManager.GetString("MinimapSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, EdgeTool is unable to provide full support for this model..
        /// </summary>
        public static string ModelColorWarning {
            get {
                return ResourceManager.GetString("ModelColorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model has used Models/Model/Triangle/Vertex/@Color which EdgeTool hasn&apos;t supported yet. The model will be rendered in white color..
        /// </summary>
        public static string ModelColorWarningDetails {
            get {
                return ResourceManager.GetString("ModelColorWarningDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Viewer.
        /// </summary>
        public static string ModelViewer {
            get {
                return ResourceManager.GetString("ModelViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: Hold left button to drag left, right, forward and backward (X and Z axis). Hold right button to drag up and down (Y axis). Scroll to change Field of View. You can pick background color on the right..
        /// </summary>
        public static string ModelViewerHint {
            get {
                return ResourceManager.GetString("ModelViewerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here if you want to modify mappings.xml manually..
        /// </summary>
        public static string ModifyMappingXmlLink {
            get {
                return ResourceManager.GetString("ModifyMappingXmlLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: /mod.xml..
        /// </summary>
        public static string ModXmlNotFound {
            get {
                return ResourceManager.GetString("ModXmlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: @MusicJava is out of range (0-11)! 00_menus will be used..
        /// </summary>
        public static string MusicJavaOutOfRange {
            get {
                return ResourceManager.GetString("MusicJavaOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: @Music is out of range (0-24)! 06_Kakkoi will be used..
        /// </summary>
        public static string MusicOutOfRange {
            get {
                return ResourceManager.GetString("MusicOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should use it if you are using the latest Steam non-demo version of the game..
        /// </summary>
        public static string NewEtxConfirmDetails {
            get {
                return ResourceManager.GetString("NewEtxConfirmDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to use the new version of .etx files?.
        /// </summary>
        public static string NewEtxConfirmTitle {
            get {
                return ResourceManager.GetString("NewEtxConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (NOT EXISTS).
        /// </summary>
        public static string NotExists {
            get {
                return ResourceManager.GetString("NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no updates available..
        /// </summary>
        public static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.ini for EDGE _Demo.
        /// </summary>
        public static string OpenSettingsIniEdgeDemoItem {
            get {
                return ResourceManager.GetString("OpenSettingsIniEdgeDemoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.ini for EDGE E_pic.
        /// </summary>
        public static string OpenSettingsIniEdgeEpicItem {
            get {
                return ResourceManager.GetString("OpenSettingsIniEdgeEpicItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.ini for ED_GE.
        /// </summary>
        public static string OpenSettingsIniEdgeItem {
            get {
                return ResourceManager.GetString("OpenSettingsIniEdgeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where you want to save.
        /// </summary>
        public static string OutputPathSelectorTitle {
            get {
                return ResourceManager.GetString("OutputPathSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Image.
        /// </summary>
        public static string PngFilter {
            get {
                return ResourceManager.GetString("PngFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing....
        /// </summary>
        public static string Preparing {
            get {
                return ResourceManager.GetString("Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prism.
        /// </summary>
        public static string Prism {
            get {
                return ResourceManager.GetString("Prism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to proceed?.
        /// </summary>
        public static string ProceedConfirm {
            get {
                return ResourceManager.GetString("ProceedConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project XML.
        /// </summary>
        public static string ProjectFilter {
            get {
                return ResourceManager.GetString("ProjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the project you would like to use.
        /// </summary>
        public static string ProjectPathSelectorTitle {
            get {
                return ResourceManager.GetString("ProjectPathSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record _KeyEvent.
        /// </summary>
        public static string RecordKeyEventItem {
            get {
                return ResourceManager.GetString("RecordKeyEventItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re_fresh.
        /// </summary>
        public static string RefreshEdgeModsButton {
            get {
                return ResourceManager.GetString("RefreshEdgeModsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh _global player progress.
        /// </summary>
        public static string RefreshGlobalPlayerProgressButton {
            get {
                return ResourceManager.GetString("RefreshGlobalPlayerProgressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires network..
        /// </summary>
        public static string RequireNetworkTooltip {
            get {
                return ResourceManager.GetString("RequireNetworkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlarger.
        /// </summary>
        public static string ResizerGrow {
            get {
                return ResourceManager.GetString("ResizerGrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrinker.
        /// </summary>
        public static string ResizerShrink {
            get {
                return ResourceManager.GetString("ResizerShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizer{0}: X and/or Y-coordinate is out of range! The resizer will be visible in the level but will neither function nor collide with the player block and might cause the game to crash..
        /// </summary>
        public static string ResizerXYOutOfRange {
            get {
                return ResourceManager.GetString("ResizerXYOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resizer{0}: Z-coordinate is out of range! This could cause the game to crash..
        /// </summary>
        public static string ResizerZOutOfRange {
            get {
                return ResourceManager.GetString("ResizerZOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Run EDGE.
        /// </summary>
        public static string RunGameButton {
            get {
                return ResourceManager.GetString("RunGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select _user:.
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (How?).
        /// </summary>
        public static string ShowMappingXmlHelpLink {
            get {
                return ResourceManager.GetString("ShowMappingXmlHelpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _minimap.
        /// </summary>
        public static string ShowMinimapItem {
            get {
                return ResourceManager.GetString("ShowMinimapItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sort....
        /// </summary>
        public static string SortButton {
            get {
                return ResourceManager.GetString("SortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By _achieved.
        /// </summary>
        public static string SortByAchieved {
            get {
                return ResourceManager.GetString("SortByAchieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By AP_I name.
        /// </summary>
        public static string SortByApiName {
            get {
                return ResourceManager.GetString("SortByApiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By _description.
        /// </summary>
        public static string SortByDescription {
            get {
                return ResourceManager.GetString("SortByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By _global player progress.
        /// </summary>
        public static string SortByGlobalPlayerProgress {
            get {
                return ResourceManager.GetString("SortByGlobalPlayerProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By _points.
        /// </summary>
        public static string SortByPoints {
            get {
                return ResourceManager.GetString("SortByPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By _title.
        /// </summary>
        public static string SortByTitle {
            get {
                return ResourceManager.GetString("SortByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default _order.
        /// </summary>
        public static string SortDefaultOrder {
            get {
                return ResourceManager.GetString("SortDefaultOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn Point.
        /// </summary>
        public static string SpawnPoint {
            get {
                return ResourceManager.GetString("SpawnPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: Z-coordinate of @SpawnPoint is less than -20, the level will stuck restarting itself over and over!.
        /// </summary>
        public static string SpawnPointOutOfRange {
            get {
                return ResourceManager.GetString("SpawnPointOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open after (de)compilation:.
        /// </summary>
        public static string StartAfterCompileLabel {
            get {
                return ResourceManager.GetString("StartAfterCompileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start the (de)compiled file..
        /// </summary>
        public static string StartDecompiledFileFailed {
            get {
                return ResourceManager.GetString("StartDecompiledFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to selecte_d profile.
        /// </summary>
        public static string SwitchToSelectedProfileButton {
            get {
                return ResourceManager.GetString("SwitchToSelectedProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level: @Theme is out of range (0-3)! White theme (0) will be used..
        /// </summary>
        public static string ThemeOutOfRange {
            get {
                return ResourceManager.GetString("ThemeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Toolbox....
        /// </summary>
        public static string ToolboxButton {
            get {
                return ResourceManager.GetString("ToolboxButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Triangle must have three Vertex child elements!.
        /// </summary>
        public static string TriangleVertexCountError {
            get {
                return ResourceManager.GetString("TriangleVertexCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Unable to recognize this element under {1} element. It will be ignored..
        /// </summary>
        public static string UnrecognizedChildElement {
            get {
                return ResourceManager.GetString("UnrecognizedChildElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized coordinate!.
        /// </summary>
        public static string UnrecognizedCoordinate {
            get {
                return ResourceManager.GetString("UnrecognizedCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized event!.
        /// </summary>
        public static string UnrecognizedEvent {
            get {
                return ResourceManager.GetString("UnrecognizedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized level size!.
        /// </summary>
        public static string UnrecognizedSize {
            get {
                return ResourceManager.GetString("UnrecognizedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: @Angle or @FieldOfView is larger than 184! 184 will be used for this value..
        /// </summary>
        public static string ValueOutOfRange {
            get {
                return ResourceManager.GetString("ValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _selected models to model viewer.
        /// </summary>
        public static string ViewerAddSelectedModelButton {
            get {
                return ResourceManager.GetString("ViewerAddSelectedModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Apply selected animation to all models in model viewer (right click if you want to play only once).
        /// </summary>
        public static string ViewerApplySelectedAnimButton {
            get {
                return ResourceManager.GetString("ViewerApplySelectedAnimButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line 1 Column 1 must be &apos;id&apos;!.
        /// </summary>
        public static string XlsFormatIDError {
            get {
                return ResourceManager.GetString("XlsFormatIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: @Zoom is out of range (1-{1})! Zoom level 1 will be used..
        /// </summary>
        public static string ZoomOutOfRange {
            get {
                return ResourceManager.GetString("ZoomOutOfRange", resourceCulture);
            }
        }
    }
}
